org: eduardofidera
app: serverless-api
service: serverless-api

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  environment:
    DATABASE_ENDPOINT: ${param:databaseEndpoint}

functions: # add 4 functions for CRUD
  login:
    handler: handler.loginHandler
    events:
      - http:
          path: /auth/login
          method: post
          cors: true
  create:
    handler: handler.createNoteHandler
    events:
      - http:
          path: notes
          method: post
          cors: true
  getOne:
    handler: handler.getOneNoteHandler
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
  getAll:
    handler: handler.getAllNotesHandler
    events:
      - http:
          path: notes
          method: get
          cors: true
  update:
    handler: handler.updateNoteHandler
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
  delete:
    handler: handler.deleteNoteHandler
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
  authorizer:
    handler: handler.authorizationHandler
    cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
